import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

const WixMadeforText = localFont({
  src: "./fonts/WixMadeforText-VariableFont_wght.ttf",
  variable: "--font-wix-madefor-text",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SMS - Front end Dev Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${WixMadeforText.variable} antialiased`}>
        <main className="w-full flex flex-col h-[100vh]">
          {/* Fixed header */}
          <div className="fixed w-full top-0 z-10">
            <Header />
          </div>

          <div className="flex w-full h-full pt-[10vh]">
            {/* Fixed sidebar */}
            <div className="fixed w-[20%] h-[80vh]">
              <Sidebar />
            </div>

            {/* Content section with scrollable content */}
            <div className="w-[80%] ml-[20%] bg-[#F1F5F8] h-full overflow-y-auto">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
